### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by brett-kimball** [gbannerman/mopidy-pibox#17]
This is by far the best "jukebox" extension for Mopidy that I have used.  I initially intended to request some new features, but have mostly come to my senses in that regard.

The one "malfunction" I have encountered using the extension is with the search box.  **If there is preceding or trailing whitespace in the search string, no results are returned.**  It may be necessary to strip the whitespace before perfoming the search query.

Also to leave the search screen without selecting a song it is necessary to use the browser's "back" button.

Thanks for a great interface!

**Comment by gbannerman** [comment]
@brett-kimball I am 2 years late 😅 but this has been fixed in `0.9.1` which is now released on pypi.

Thanks for reporting it and for the positive feedback.

I might be spending a bit more time on this project, so if you're still using it and have feedback / feature requests then please let me know!
