### ISSUE TITLE
Switch on feature "Admins controls to pause/resume playback or skip current track"

### ISSUE THREAD

**Issue by BierBierBloxberg** [gbannerman/mopidy-pibox#49]
Hi,

maybe not a bug, but how can I switch on the above mentioned feature. Or how can I log in as admin?

Thanks for your support?

**Comment by gbannerman** [comment]
Hi @BierBierBloxberg,

You can enable the admin controls by tapping/clicking the pibox logo on the home screen 7 times. I need to document this somewhere, so will make sure to do that. See this video below:

https://github.com/user-attachments/assets/bed92513-dcee-4a1f-b8f9-aaa9409204ee

I went with this approach because it's a low effort way to enable it without it being easily discoverable. If you refresh the page you'll need to do the process again.

I've thought about coming up with a different approach like a password or something similar, so if you have any feedback about this or pibox in general then please let me know!

**Comment by gbannerman** [comment]
I've added an FAQ to the Wiki [which includes this information](https://github.com/gbannerman/mopidy-pibox/wiki/FAQs#how-do-i-get-access-to-the-admin-controls).

I'm going to close this issue, but if you have other feedback please [open another issue](https://github.com/gbannerman/mopidy-pibox/issues/new) or [start a discussion](https://github.com/gbannerman/mopidy-pibox/discussions/new?category=ideas).
